name: test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  node:
    name: v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies using Yarn
        run: yarn

      - name: Build Packages
        run: yarn build

      - name: Test
        run: yarn test

      - name: Node.js integrity check
        run: yarn bob check
